### ISSUE TITLE
Unicode decode error

### ISSUE THREAD

**Issue by wired4life4** [chatcannon/pytnt#10]
Hello,

I just found this and am not sure if it is still in development. I am wondering if there is anything wrong with this code block as it throws up an ascii error on some files but works fine with others. 

```
tntclass = tnt.TNTfile(path) # using pytnt module, error occurs here    
tntdelay = tntclass.DELAY # output of delay tables
tmparameters = tntclass.__getattr__ #This is the parameter list
data = tntclass.DATA #This is the data
```

Traceback (most recent call last):

  File "C:\Users\...\tntanalysis.py", line 28, in <module>
    tntclass = tnt.TNTfile(path) # using pytnt module

  File "C:\Users\...\pytnt\pytnt\processTNT.py", line 62, in __init__
    delay_name = read_pascal_string(search_region[offset:])

  File "C:\Users\...\pytnt\pytnt\utils.py", line 77, in read_pascal_string
    text = str(text, encoding)

UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 38: ordinal not in range(128). 

Thanks in advance :)

**Comment by chatcannon** [comment]
I haven't done anything with this project for years, because I haven't been using NMR myself and also haven't had any pull requests from anyone else. I could have a look into the error if you send me some examples of files that have not been working.

Alternatively you could look at https://github.com/jjhelmus/nmrglue which incorporates some of the code I wrote for pytnt but is more actively maintained. (See the edit history at https://github.com/jjhelmus/nmrglue/commits/master/nmrglue/fileio/tecmag.py )

**Comment by chatcannon** [comment]
I just saw that you had already seen and commented on nmrglue yourself. I guess it would be a good idea for me to try to merge nmrglue's improvements into this repo and also open a pull request to get my improvements added there.

**Comment by wired4life4** [comment]
Thanks for the reply, it is a huge convenience to have a code read out the data tables! I can send you some example files, however, I cannot attach them here, and I don't see any way to message you directly. What would be the best way to send them to you?

It is strange, I tried the same code on a different PC and it ran without error, both using Windows 10, Python 3.8, and the same Spyder IDE.

**Comment by chatcannon** [comment]
It looks like the code that searches for delay tables has found some data that just happens to look like a delay table header but is not. It then tries to read in a non-existent delay table.

**Comment by chatcannon** [comment]
Hopefully the changes in #15 will reduce the likelihood of this occurring and give you a system that works while I think of a more robust solution.

**Comment by wired4life4** [comment]
It works! Thank you very much!
